# Generated by Django 5.2.17 on 2026-08-26 11:25

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_alter_property_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000, verbose_name='message')),
                ('preferred_move_in_date', models.DateField(blank=True, null=True, verbose_name='preferred move-in date')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('answered', 'Answered'), ('closed', 'Closed'), ('expired', 'Expired unanswered')], default='sent', max_length=16, verbose_name='status')),
                ('response', models.TextField(blank=True, max_length=1000, verbose_name='response')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='responded at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries_answered', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries_sent', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['sender', '-created_at'], name='inquiry_sender_idx'), models.Index(fields=['unit', 'sender', '-created_at'], name='inquiry_unit_sender_idx'), models.Index(fields=['status', 'created_at'], name='inquiry_queue_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('sent',))), fields=('unit', 'sender'), name='inquiry_one_open_per_unit_and_sender'), models.CheckConstraint(condition=models.Q(('response', ''), models.Q(('responded_by__isnull', False), ('responded_at__isnull', False)), _connector='OR'), name='inquiry_response_is_attributed'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'answered'), _negated=True), models.Q(('response', ''), _negated=True), _connector='OR'), name='inquiry_answered_has_a_response'), models.CheckConstraint(condition=models.Q(('message', ''), _negated=True), name='inquiry_message_not_empty')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_saved', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved property',
                'verbose_name_plural': 'Saved properties',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['user', '-created_at'], name='saved_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'property_saved'), name='saved_unique_per_user_and_property')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
