# Generated by Django 5.2.17 on 2026-08-24 19:52

import accounts.models
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='business name')),
                ('kra_pin', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='A KRA PIN looks like A123456789Z.', regex='^[AP]\\d{9}[A-Z]$')], verbose_name='KRA PIN')),
                ('national_id', models.CharField(blank=True, help_text='Write-only in the API. Never returned in a response.', max_length=20, verbose_name='national ID')),
                ('id_document_key', models.CharField(blank=True, help_text='Key in the PRIVATE documents bucket. Never the public CDN (ADR-007).', max_length=500, verbose_name='ID document key')),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=16, verbose_name='verification status')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('payout_phone', models.CharField(blank=True, help_text='M-Pesa number. Reserved for when payments ship.', max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a Kenyan number in international format, e.g. +254712345678.', regex='^\\+254[17]\\d{8}$')], verbose_name='payout phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landlord profile',
                'verbose_name_plural': 'Landlord profiles',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(blank=True, help_text="Must match one of the university's student email domains.", max_length=254, verbose_name='student email')),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=16, verbose_name='verification status')),
                ('verification_method', models.CharField(blank=True, choices=[('email_domain', 'Student email domain'), ('student_id_upload', 'Student ID document upload')], help_text='Blank until verification succeeds.', max_length=24, verbose_name='verification method')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='rejection reason')),
                ('grace_period_ends_at', models.DateTimeField(blank=True, help_text='Set at signup when the university gates actions on verification. Read access never depends on it (ADR-003).', null=True, verbose_name='grace period ends')),
                ('year_of_study', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year of study')),
                ('course', models.CharField(blank=True, max_length=200, verbose_name='course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student profile',
                'verbose_name_plural': 'Student profiles',
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UniversityStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='job title')),
                ('can_review_verifications', models.BooleanField(default=True, verbose_name='can review verifications')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'University staff profile',
                'verbose_name_plural': 'University staff profiles',
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a Kenyan number in international format, e.g. +254712345678.', regex='^\\+254[17]\\d{8}$')], verbose_name='phone number')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='phone verified')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('avatar_url', models.URLField(blank=True, verbose_name='avatar URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text="The only meaning of 'platform administrator'. Not settable via the API.", verbose_name='platform staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CaretakerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('manage_units', 'Create and edit units'), ('manage_vacancy', 'Set vacancy counts'), ('manage_photos', 'Upload and manage photos'), ('set_availability', 'Set availability'), ('resolve_tenancy_claims', 'Confirm or dispute tenancy claims'), ('respond_inquiries', 'Respond to inquiries')], max_length=32), blank=True, default=list, help_text='A subset of CaretakerPermission. Values outside it are rejected on write, so the list cannot drift from the code that checks it.', size=None, verbose_name='permissions')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(help_text='The landlord. PROTECT so the audit trail cannot be deleted away.', on_delete=django.db.models.deletion.PROTECT, related_name='caretaker_assignments_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caretaker assignment',
                'verbose_name_plural': 'Caretaker assignments',
                'ordering': ['-granted_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
