# Generated by Django 5.2.17 on 2026-08-24 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('properties', '0001_initial'),
        ('universities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretakerassignment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_assignments', to='properties.property'),
        ),
        migrations.AddField(
            model_name='caretakerassignment',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caretaker_assignments_revoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caretakerassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landlord_verifications_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='universities.university'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Null for the automated email-domain path.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_verifications_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='universitystaffprofile',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='universities.university'),
        ),
        migrations.AddField(
            model_name='universitystaffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-date_joined'], name='user_joined_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number', ''), _negated=True), fields=('phone_number',), name='user_phone_unique_when_set'),
        ),
        migrations.AddIndex(
            model_name='caretakerassignment',
            index=models.Index(fields=['property', 'is_active'], name='caretaker_property_idx'),
        ),
        migrations.AddIndex(
            model_name='caretakerassignment',
            index=models.Index(fields=['user', 'is_active'], name='caretaker_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='caretakerassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'property'), name='caretaker_one_active_assignment'),
        ),
        migrations.AddConstraint(
            model_name='caretakerassignment',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', True), ('revoked_at__isnull', False), _connector='OR'), name='caretaker_revoked_has_timestamp'),
        ),
        migrations.AddIndex(
            model_name='landlordprofile',
            index=models.Index(fields=['verification_status'], name='landlord_verif_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='landlordprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verification_status', 'verified'), _negated=True), ('verified_at__isnull', False), _connector='OR'), name='landlord_verified_has_timestamp'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['university', 'verification_status'], name='student_verif_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('student_email', ''), _negated=True), fields=('student_email',), name='student_email_unique_when_set'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verification_status', 'verified'), _negated=True), models.Q(('verification_method', ''), _negated=True), _connector='OR'), name='student_verified_has_a_method'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verification_status', 'rejected'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='student_rejected_has_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('year_of_study__isnull', True), models.Q(('year_of_study__gte', 1), ('year_of_study__lte', 8)), _connector='OR'), name='student_year_of_study_range'),
        ),
        migrations.AddIndex(
            model_name='universitystaffprofile',
            index=models.Index(fields=['university', 'is_active'], name='unistaff_active_idx'),
        ),
    ]
