# Generated by Django 5.2.17 on 2026-08-25 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='student email')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='token hash')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consumed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Email verification token',
                'verbose_name_plural': 'Email verification tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', '-created_at'], name='emailtok_profile_idx'), models.Index(fields=['email', '-created_at'], name='emailtok_email_idx')],
            },
        ),
    ]
