# Generated by Django 5.2.17 on 2026-08-25 20:54

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(blank=True, max_length=255, verbose_name='storage key')),
                ('content_type', models.CharField(max_length=64, verbose_name='content type')),
                ('byte_size', models.PositiveIntegerField(verbose_name='size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('delete_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='delete attempts')),
                ('last_delete_error', models.CharField(blank=True, max_length=255, verbose_name='last delete error')),
            ],
            options={
                'verbose_name': 'Verification document',
                'verbose_name_plural': 'Verification documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['deleted_at', 'uploaded_at'], name='verifdoc_retention_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', True), models.Q(('storage_key', ''), _negated=True)), models.Q(('deleted_at__isnull', False), ('storage_key', '')), _connector='OR'), name='verifdoc_deleted_has_no_key'), models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='verifdoc_size_positive')],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_label', models.CharField(max_length=255, verbose_name='reviewer')),
                ('purpose', models.CharField(choices=[('review', 'Reviewing a verification request'), ('audit', 'Responding to an audit or a subject access request'), ('support', 'Investigating a support ticket')], max_length=16, verbose_name='purpose')),
                ('request_id', models.CharField(blank=True, max_length=64, verbose_name='request id')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_accesses', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_log', to='accounts.verificationdocument')),
            ],
            options={
                'verbose_name': 'Document access log',
                'verbose_name_plural': 'Document access log',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['document', '-accessed_at'], name='doclog_document_idx'), models.Index(fields=['reviewer', '-accessed_at'], name='doclog_reviewer_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reviewer_label', ''), _negated=True), name='doclog_names_a_reader')],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Awaiting review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16, verbose_name='status')),
                ('decision_reason', models.CharField(blank=True, max_length=255, verbose_name='decision reason')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('attempt', models.PositiveSmallIntegerField(default=1, verbose_name='attempt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='accounts.verificationdocument')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='accounts.studentprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Internal. Never serialised to the student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification request',
                'verbose_name_plural': 'Verification requests',
                'ordering': ['created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['status', 'created_at'], name='verifreq_queue_idx'), models.Index(fields=['profile', '-created_at'], name='verifreq_profile_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('pending',))), fields=('profile',), name='verifreq_one_open_per_profile'), models.CheckConstraint(condition=models.Q(('status', 'pending'), ('reviewed_at__isnull', False), _connector='OR'), name='verifreq_decision_has_a_time'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('decision_reason', ''), _negated=True), _connector='OR'), name='verifreq_rejection_has_a_reason')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
