# Generated by Django 5.2.17 on 2026-08-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_verificationdocument_documentaccesslog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='review_gated_at_registration',
            field=models.BooleanField(default=False, verbose_name='reviews gated at registration'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='signup_policy_at_registration',
            field=models.CharField(choices=[('open', 'Open — verification is not mentioned at signup'), ('verification_encouraged', 'Encouraged — the student is prompted and can skip'), ('verification_required', 'Required — signup completes only for a verified student')], default='open', max_length=24, verbose_name='signup policy at registration'),
        ),
    ]
