# Generated by Django 5.2.17 on 2026-08-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_review_gated_at_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='erased_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='erased at'),
        ),
    ]
