# Generated by Django 5.2.17 on 2026-08-26 11:15

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_erased_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccesslog',
            name='subject_token',
            field=models.CharField(db_index=True, default=secrets.token_hex, max_length=64, verbose_name='subject token'),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='verification_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_log', to='accounts.verificationrequest'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='subject_token',
            field=models.CharField(default=secrets.token_hex, editable=False, max_length=64, verbose_name='subject token'),
        ),
        migrations.AlterField(
            model_name='documentaccesslog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_log', to='accounts.verificationdocument'),
        ),
        migrations.AddConstraint(
            model_name='documentaccesslog',
            constraint=models.CheckConstraint(condition=models.Q(('subject_token', ''), _negated=True), name='doclog_has_a_token'),
        ),
    ]
