# Generated by Django 5.2.17 on 2026-08-27 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_documentaccesslog_subject_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErasureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', max_length=16)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erasure_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Erasure request',
                'verbose_name_plural': 'Erasure requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
