# Generated by Django 5.2.17 on 2026-08-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_erasurerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasurerequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erasurerequest',
            name='executes_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='erasurerequest',
            name='status',
            field=models.CharField(choices=[('cooling_off', 'Cooling off'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled by the subject')], default='cooling_off', max_length=16),
        ),
        migrations.AddIndex(
            model_name='erasurerequest',
            index=models.Index(fields=['status', 'executes_after'], name='erasure_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='erasurerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cooling_off'), _negated=True), ('executes_after__isnull', False), _connector='OR'), name='erasure_cooling_off_has_a_deadline'),
        ),
        migrations.AddConstraint(
            model_name='erasurerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancelled_at__isnull', False), _connector='OR'), name='erasure_cancelled_has_a_time'),
        ),
    ]
