# Generated by Django 5.2.17 on 2026-08-25 06:23

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.db.models.manager
import tenancies.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='submitted', max_length=20, verbose_name='status')),
                ('move_in_date', models.DateField(verbose_name='requested move-in date')),
                ('intended_months', models.PositiveSmallIntegerField(verbose_name='intended stay (months)')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('decision_note', models.TextField(blank=True, verbose_name='decision note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, help_text='The landlord or an assigned caretaker.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_decisions', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TenancyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('monthly_rent_kes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monthly rent (KES)')),
                ('status', models.CharField(choices=[('pending', 'Awaiting confirmation'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed between the parties'), ('escalated', 'Escalated to platform admins'), ('withdrawn', 'Withdrawn by the claimant'), ('expired', 'Expired')], default='pending', max_length=16, verbose_name='status')),
                ('confirmation_deadline', models.DateTimeField(help_text='Silence past this point auto-confirms the claim.', verbose_name='confirmation deadline')),
                ('is_retrospective', models.BooleanField(default=False, help_text="The stay predates the property's presence on the platform. For analytics and the operations queue ONLY — never for display and never for weighting (ADR-004). A flag that reaches the UI becomes a second class of review.", verbose_name='retrospective')),
                ('dispute_reason', models.CharField(blank=True, choices=[('dates_incorrect', 'The stay happened; the dates are wrong'), ('never_tenanted', 'This person never lived here'), ('duplicate', 'Already covered by an existing tenancy')], help_text='Enumerated, because an untyped dispute can only be routed to a human.', max_length=24, verbose_name='dispute reason')),
                ('dispute_note', models.TextField(blank=True, help_text='Additional context. Never a substitute for the enumerated reason.', verbose_name='dispute note')),
                ('disputed_at', models.DateTimeField(blank=True, null=True, verbose_name='disputed at')),
                ('proposed_start_date', models.DateField(blank=True, null=True, verbose_name='proposed start date')),
                ('proposed_end_date', models.DateField(blank=True, null=True, verbose_name='proposed end date')),
                ('counter_start_date', models.DateField(blank=True, null=True, verbose_name='counter start date')),
                ('counter_end_date', models.DateField(blank=True, null=True, verbose_name='counter end date')),
                ('tenant_accepted_correction_at', models.DateTimeField(blank=True, null=True, verbose_name='tenant accepted the correction at')),
                ('escalation_reason', models.CharField(blank=True, choices=[('counter_unresolved', 'Which set of dates is right'), ('correction_defeats_review', 'Whether a review-defeating correction is honest'), ('identity_disputed', 'Whether this person lived here at all'), ('duplicate_unmatched', 'Whether an existing tenancy covers this')], help_text='What the administrator has to decide. The queue sorts on this.', max_length=26, verbose_name='escalation reason')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='escalated at')),
                ('dispute_withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='dispute withdrawn at')),
                ('escalation_deadline', models.DateTimeField(blank=True, help_text="The deadline binds the PLATFORM, not the tenant. Past it the claim confirms in the tenant's favour (ADR-004).", null=True, verbose_name='escalation deadline')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancy_claims', to=settings.AUTH_USER_MODEL)),
                ('disputed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Null when the claim resolved by timeout: silence has no author.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_claims', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancy_claims', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Tenancy claim',
                'verbose_name_plural': 'Tenancy claims',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_source', models.CharField(choices=[('application', 'Accepted on-platform application'), ('landlord', 'Confirmed by the landlord'), ('caretaker', 'Confirmed by a caretaker'), ('auto', 'Auto-confirmed: the confirmation window elapsed'), ('admin', 'Resolved by a platform administrator'), ('dispute_timeout', 'Auto-resolved: the dispute window elapsed')], max_length=20, verbose_name='confirmation source')),
                ('confirmed_at', models.DateTimeField(verbose_name='confirmed at')),
                ('was_disputed', models.BooleanField(default=False, help_text='A dispute occurred, whatever its outcome. A fact, not a display decision.', verbose_name='was disputed')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('monthly_rent_kes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monthly rent (KES)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=16, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, help_text='The witnessed path (ADR-004).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenancies', to='tenancies.application')),
                ('confirmed_by', models.ForeignKey(blank=True, help_text="Null for 'auto' and 'dispute_timeout', which have no actor.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenancy_confirmations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='properties.unit')),
                ('claim', models.ForeignKey(blank=True, help_text="The claimed path. PROTECT, not SET_NULL: the review's dispute annotation is derived from this record, so it must survive.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='tenancies.tenancyclaim')),
            ],
            options={
                'verbose_name': 'Tenancy',
                'verbose_name_plural': 'Tenancies',
                'ordering': ['-start_date'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['unit', 'status'], name='application_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', '-created_at'], name='application_applicant_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('submitted', 'under_review'))), fields=('unit', 'applicant'), name='application_one_open_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('decided_at__isnull', True), ('decided_by__isnull', False), _connector='OR'), name='application_decision_has_an_author'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('intended_months__gte', 1)), name='application_intended_months_positive'),
        ),
        migrations.AddIndex(
            model_name='tenancyclaim',
            index=models.Index(fields=['status', 'confirmation_deadline'], name='claim_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancyclaim',
            index=models.Index(fields=['claimant', '-created_at'], name='claim_claimant_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancyclaim',
            index=models.Index(fields=['is_retrospective'], name='claim_retrospective_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancyclaim',
            index=models.Index(fields=['escalation_reason', 'escalated_at'], name='claim_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancyclaim',
            index=models.Index(fields=['status', 'escalation_deadline'], name='claim_escalation_sla_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancyclaim',
            index=models.Index(fields=['disputed_by', '-disputed_at'], name='claim_disputer_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenancyclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'disputed', 'escalated'))), fields=('unit', 'claimant'), name='claim_one_open_per_unit_and_claimant'),
        ),
        migrations.AddConstraint(
            model_name='tenancyclaim',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='claim_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='tenancyclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('confirmed', 'withdrawn', 'expired')), _negated=True), ('resolved_at__isnull', False), _connector='OR'), name='claim_terminal_status_has_a_resolution_time'),
        ),
        migrations.AddConstraint(
            model_name='tenancyclaim',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_rent_kes__gt', 0)), name='claim_rent_positive'),
        ),
        migrations.AddConstraint(
            model_name='tenancyclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('disputed', 'escalated')), _negated=True), models.Q(models.Q(('dispute_reason', ''), _negated=True), ('disputed_by__isnull', False), ('disputed_at__isnull', False)), _connector='OR'), name='claim_dispute_is_typed_and_attributed'),
        ),
        migrations.AddConstraint(
            model_name='tenancyclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dispute_reason', 'dates_incorrect'), _negated=True), ('proposed_start_date__isnull', False), _connector='OR'), name='claim_correction_states_its_dates'),
        ),
        migrations.AddConstraint(
            model_name='tenancyclaim',
            constraint=models.CheckConstraint(condition=models.Q(('proposed_end_date__isnull', True), ('proposed_end_date__gte', models.F('proposed_start_date')), _connector='OR'), name='claim_proposed_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='tenancyclaim',
            constraint=models.CheckConstraint(condition=models.Q(('counter_end_date__isnull', True), ('counter_end_date__gte', models.F('counter_start_date')), _connector='OR'), name='claim_counter_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='tenancyclaim',
            constraint=models.CheckConstraint(condition=models.Q(('counter_start_date__isnull', True), ('proposed_start_date__isnull', False), _connector='OR'), name='claim_counter_answers_a_correction'),
        ),
        migrations.AddConstraint(
            model_name='tenancyclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('escalated_at__isnull', True), ('escalation_deadline__isnull', True)), models.Q(('escalated_at__isnull', False), ('escalation_deadline__isnull', False)), _connector='OR'), name='claim_escalation_has_a_deadline'),
        ),
        migrations.AddConstraint(
            model_name='tenancyclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'escalated'), _negated=True), models.Q(models.Q(('escalation_reason', ''), _negated=True), ('escalated_at__isnull', False)), _connector='OR'), name='claim_escalation_names_its_question'),
        ),
        migrations.AddConstraint(
            model_name='tenancyclaim',
            constraint=models.CheckConstraint(condition=models.Q(('escalation_reason', ''), models.Q(('dispute_reason', 'dates_incorrect'), ('escalation_reason__in', ('counter_unresolved', 'correction_defeats_review'))), models.Q(('dispute_reason', 'never_tenanted'), ('escalation_reason__in', ('identity_disputed',))), models.Q(('dispute_reason', 'duplicate'), ('escalation_reason__in', ('duplicate_unmatched',))), _connector='OR'), name='claim_escalation_matches_its_dispute'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['tenant', '-start_date'], name='tenancy_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['unit', 'status'], name='tenancy_unit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['confirmation_source'], name='tenancy_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='tenancy_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.UniqueConstraint(fields=('unit', 'tenant', 'start_date'), name='tenancy_unique_per_unit_tenant_start'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmation_source', 'application'), ('application__isnull', False), ('claim__isnull', True)), models.Q(models.Q(('confirmation_source', 'application'), _negated=True), ('claim__isnull', False), ('application__isnull', True)), _connector='OR'), name='tenancy_source_matches_its_origin'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'active')), expressions=[('unit', '='), ('tenant', '='), (tenancies.models.TenancyDateRange('start_date', 'end_date'), '&&')], name='tenancy_no_overlapping_active_stay'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmation_source__in', ('auto', 'dispute_timeout')), ('confirmed_by__isnull', True)), models.Q(models.Q(('confirmation_source__in', ('auto', 'dispute_timeout')), _negated=True), ('confirmed_by__isnull', False)), _connector='OR'), name='tenancy_confirmed_by_matches_source'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_rent_kes__gt', 0)), name='tenancy_rent_positive'),
        ),
    ]
