# Generated by Django 5.2.17 on 2026-08-25 05:53

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='submitted', max_length=20, verbose_name='status')),
                ('move_in_date', models.DateField(verbose_name='requested move-in date')),
                ('intended_months', models.PositiveSmallIntegerField(verbose_name='intended stay (months)')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('decision_note', models.TextField(blank=True, verbose_name='decision note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, help_text='The landlord or an assigned caretaker.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_decisions', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_source', models.CharField(choices=[('application', 'Accepted on-platform application'), ('landlord', 'Confirmed by the landlord'), ('caretaker', 'Confirmed by a caretaker'), ('auto', 'Auto-confirmed: the confirmation window elapsed'), ('admin', 'Resolved by a platform administrator'), ('dispute_timeout', 'Auto-resolved: the dispute window elapsed')], max_length=20, verbose_name='confirmation source')),
                ('confirmed_at', models.DateTimeField(verbose_name='confirmed at')),
                ('was_disputed', models.BooleanField(default=False, help_text='A dispute occurred, whatever its outcome. A fact, not a display decision.', verbose_name='was disputed')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('monthly_rent_kes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monthly rent (KES)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=16, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, help_text='The witnessed path (ADR-004).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenancies', to='tenancies.application')),
                ('confirmed_by', models.ForeignKey(blank=True, help_text="Null for 'auto' and 'dispute_timeout', which have no actor.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenancy_confirmations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Tenancy',
                'verbose_name_plural': 'Tenancies',
                'ordering': ['-start_date'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['unit', 'status'], name='application_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', '-created_at'], name='application_applicant_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('submitted', 'under_review'))), fields=('unit', 'applicant'), name='application_one_open_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('decided_at__isnull', True), ('decided_by__isnull', False), _connector='OR'), name='application_decision_has_an_author'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('intended_months__gte', 1)), name='application_intended_months_positive'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['tenant', '-start_date'], name='tenancy_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['unit', 'status'], name='tenancy_unit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['confirmation_source'], name='tenancy_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='tenancy_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.UniqueConstraint(fields=('unit', 'tenant', 'start_date'), name='tenancy_unique_per_unit_tenant_start'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmation_source', 'application'), _negated=True), ('application__isnull', False), _connector='OR'), name='tenancy_application_source_has_an_application'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmation_source__in', ('auto', 'dispute_timeout')), ('confirmed_by__isnull', True)), models.Q(models.Q(('confirmation_source__in', ('auto', 'dispute_timeout')), _negated=True), ('confirmed_by__isnull', False)), _connector='OR'), name='tenancy_confirmed_by_matches_source'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_rent_kes__gt', 0)), name='tenancy_rent_positive'),
        ),
    ]
