# Generated by Django 5.2.17 on 2026-08-26 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('tenancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='terminated_early',
            field=models.BooleanField(default=False, verbose_name='terminated early'),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='termination_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='termination reason'),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('disputed', 'Disputed after confirmation'), ('withdrawn', 'Withdrawn by the parties'), ('rejected', 'Rejected by an administrator')], default='confirmed', help_text='What the tenancy IS. Whether it is running is derived from the dates -- see TenancyQuerySet.current().', max_length=16, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['start_date', 'end_date'], name='tenancy_currency_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('terminated_early', True), _negated=True), models.Q(('end_date__isnull', False), models.Q(('termination_reason', ''), _negated=True)), _connector='OR'), name='tenancy_early_termination_is_dated_and_explained'),
        ),
    ]
