# Generated by Django 5.2.17 on 2026-08-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        ('tenancies', '0002_tenancy_terminated_early_tenancy_termination_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='engagement.inquiry'),
        ),
    ]
