# Generated by Django 5.2.17 on 2026-08-27 18:48

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_status'),
        ('tenancies', '0003_application_inquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_end_date', models.DateField(verbose_name='actual move-out date')),
                ('reason', models.CharField(max_length=255, verbose_name='reason')),
                ('status', models.CharField(choices=[('pending', 'Awaiting confirmation'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed between the parties'), ('escalated', 'Escalated to platform admins'), ('withdrawn', 'Withdrawn by the claimant'), ('expired', 'Expired')], default='pending', max_length=16, verbose_name='status')),
                ('confirmation_deadline', models.DateTimeField(help_text='Silence past this point auto-confirms, as with a claim.', verbose_name='confirmation deadline')),
                ('dispute_reason', models.CharField(blank=True, choices=[('dates_incorrect', 'The stay happened; the dates are wrong'), ('never_tenanted', 'This person never lived here'), ('duplicate', 'Already covered by an existing tenancy'), ('termination_date', 'The stay ended; the proposed move-out date is wrong')], max_length=24, verbose_name='dispute reason')),
                ('disputed_at', models.DateTimeField(blank=True, null=True, verbose_name='disputed at')),
                ('counter_end_date', models.DateField(blank=True, null=True, verbose_name='counter date')),
                ('escalation_reason', models.CharField(blank=True, choices=[('counter_unresolved', 'Which set of dates is right'), ('correction_defeats_review', 'Whether a review-defeating correction is honest'), ('identity_disputed', 'Whether this person lived here at all'), ('termination_defeats_review', 'Whether an early termination that removes a review right is honest'), ('duplicate_unmatched', 'Whether an existing tenancy covers this')], max_length=26, verbose_name='escalation reason')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='escalated at')),
                ('escalation_deadline', models.DateTimeField(blank=True, null=True, verbose_name='escalation deadline')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Termination request',
                'verbose_name_plural': 'Termination requests',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='tenancyclaim',
            name='claim_escalation_matches_its_dispute',
        ),
        migrations.AddField(
            model_name='tenancy',
            name='review_eligible_at',
            field=models.DateField(blank=True, null=True, verbose_name='review eligible from'),
        ),
        migrations.AlterField(
            model_name='tenancyclaim',
            name='dispute_reason',
            field=models.CharField(blank=True, choices=[('dates_incorrect', 'The stay happened; the dates are wrong'), ('never_tenanted', 'This person never lived here'), ('duplicate', 'Already covered by an existing tenancy'), ('termination_date', 'The stay ended; the proposed move-out date is wrong')], help_text='Enumerated, because an untyped dispute can only be routed to a human.', max_length=24, verbose_name='dispute reason'),
        ),
        migrations.AlterField(
            model_name='tenancyclaim',
            name='escalation_reason',
            field=models.CharField(blank=True, choices=[('counter_unresolved', 'Which set of dates is right'), ('correction_defeats_review', 'Whether a review-defeating correction is honest'), ('identity_disputed', 'Whether this person lived here at all'), ('termination_defeats_review', 'Whether an early termination that removes a review right is honest'), ('duplicate_unmatched', 'Whether an existing tenancy covers this')], help_text='What the administrator has to decide. The queue sorts on this.', max_length=26, verbose_name='escalation reason'),
        ),
        migrations.AddConstraint(
            model_name='tenancyclaim',
            constraint=models.CheckConstraint(condition=models.Q(('escalation_reason', ''), models.Q(('dispute_reason', 'dates_incorrect'), ('escalation_reason__in', ('counter_unresolved', 'correction_defeats_review'))), models.Q(('dispute_reason', 'never_tenanted'), ('escalation_reason__in', ('identity_disputed',))), models.Q(('dispute_reason', 'duplicate'), ('escalation_reason__in', ('duplicate_unmatched',))), models.Q(('dispute_reason', 'termination_date'), ('escalation_reason__in', ('counter_unresolved', 'termination_defeats_review'))), _connector='OR'), name='claim_escalation_matches_its_dispute'),
        ),
        migrations.AddField(
            model_name='terminationrequest',
            name='disputed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminations_disputed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terminationrequest',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminations_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terminationrequest',
            name='tenancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termination_requests', to='tenancies.tenancy'),
        ),
        migrations.AddIndex(
            model_name='terminationrequest',
            index=models.Index(fields=['status', 'confirmation_deadline'], name='termination_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='terminationrequest',
            index=models.Index(fields=['escalation_reason', 'escalated_at'], name='termination_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='terminationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'disputed', 'escalated'))), fields=('tenancy',), name='termination_one_open_per_tenancy'),
        ),
        migrations.AddConstraint(
            model_name='terminationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='termination_states_why'),
        ),
        migrations.AddConstraint(
            model_name='terminationrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('disputed', 'escalated')), _negated=True), models.Q(models.Q(('dispute_reason', ''), _negated=True), ('disputed_at__isnull', False)), _connector='OR'), name='termination_dispute_is_typed'),
        ),
        migrations.AddConstraint(
            model_name='terminationrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'escalated'), _negated=True), models.Q(models.Q(('escalation_reason', ''), _negated=True), ('escalated_at__isnull', False)), _connector='OR'), name='termination_escalation_names_its_question'),
        ),
        migrations.AddConstraint(
            model_name='terminationrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('confirmed', 'withdrawn', 'expired')), _negated=True), ('resolved_at__isnull', False), _connector='OR'), name='termination_terminal_has_a_resolution_time'),
        ),
    ]
