# Generated by Django 5.2.17 on 2026-08-27 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancies', '0004_terminationrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='terminationrequest',
            name='termination_dispute_is_typed',
        ),
        migrations.AddConstraint(
            model_name='terminationrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'disputed'), _negated=True), models.Q(models.Q(('dispute_reason', ''), _negated=True), ('disputed_at__isnull', False)), _connector='OR'), name='termination_dispute_is_typed'),
        ),
        migrations.AddConstraint(
            model_name='terminationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('disputed_at__isnull', True), models.Q(('dispute_reason', ''), _negated=True), _connector='OR'), name='termination_disputed_at_implies_a_reason'),
        ),
    ]
