"""
Host classification and the single absolute-URL builder (ADR-001).

ADR-001 puts the tenant boundary in a different place for public reads than for
everything else:

- **Public listing content is canonical on a tenant-neutral host**
  (``www.<domain>``). University subdomains serve the same content branded, and
  emit ``rel=canonical`` pointing here.
- **Every write and every authenticated read is strictly subdomain-scoped.**
- Internal surfaces — the admin, the schema, the health probes — are neither.

The ADR notes that this rule will erode: it lives in developers' heads, and
getting it wrong on a write endpoint is a security bug rather than a cosmetic
one. So it does not live in developers' heads. Every route is classified here,
`tests/test_architecture.py` fails on any route that is not, and absolute URLs
are built by exactly one function.
"""

from __future__ import annotations

from enum import Enum

from django.conf import settings
from django.urls import reverse


class HostClass(Enum):
    """Which host a route is served from."""

    #: Tenant-neutral, publicly cacheable, **read-only**. Reachable at
    #: ``www.<domain>``. This is what sitemaps advertise and what
    #: ``rel=canonical`` points at.
    PUBLIC_CANONICAL = "public_canonical"

    #: Served from a university subdomain and scoped to that tenant. Every
    #: write and every authenticated read belongs here.
    TENANT_SCOPED = "tenant_scoped"

    #: Neither public content nor tenant data: the Django admin, the OpenAPI
    #: schema, the health probes. Not served from either public host in
    #: production.
    API_INTERNAL = "api_internal"


# ---------------------------------------------------------------------------
# Classification
# ---------------------------------------------------------------------------

#: Whole third-party route trees, keyed by URL namespace.
#:
#: Only for trees whose individual routes are generated by a library and would
#: otherwise have to be re-listed here every time a model is registered. Our own
#: routes are always classified individually in ROUTE_HOST_CLASSES, so that
#: adding one forces a decision.
NAMESPACE_HOST_CLASSES: dict[str, HostClass] = {
    # django.contrib.admin generates ~6 routes per registered ModelAdmin.
    # Internal by definition; never exposed on a public host.
    "admin": HostClass.API_INTERNAL,
}

#: Every route we define, by fully-qualified URL name.
#:
#: An unclassified route fails ``test_every_route_is_classified``. That is the
#: point: adding a route must force the decision rather than inheriting one.
ROUTE_HOST_CLASSES: dict[str, HostClass] = {
    # -- Internal ----------------------------------------------------------
    "schema": HostClass.API_INTERNAL,
    "swagger-ui": HostClass.API_INTERNAL,
    "redoc": HostClass.API_INTERNAL,
    "health-live": HostClass.API_INTERNAL,
    "health-ready": HostClass.API_INTERNAL,
    # -- Public, read-only -------------------------------------------------
    # Function-based, GET-only, AllowAny. These are the only routes today that
    # can honestly be served from the neutral host: a DRF router route cannot,
    # because one URL name covers both the safe and the unsafe methods.
    "rentals:featured-rentals": HostClass.PUBLIC_CANONICAL,
    "rentals:recent-rentals": HostClass.PUBLIC_CANONICAL,
    "reviews:rental-reviews": HostClass.PUBLIC_CANONICAL,
    "reviews:rental-review-statistics": HostClass.PUBLIC_CANONICAL,
    "reviews:recent-reviews": HostClass.PUBLIC_CANONICAL,
    "reviews:top-rated-reviews": HostClass.PUBLIC_CANONICAL,
    # -- Tenant-scoped: the tenant's own configuration ---------------------
    # Unauthenticated and read-only, but NOT public canonical: the response is
    # the tenant's branding, so it is by definition not tenant-neutral. The
    # neutral host has no tenant and correctly gets a 404 here.
    "universities:tenant-config": HostClass.TENANT_SCOPED,
    # -- Tenant-scoped: authentication ------------------------------------
    "accounts:api-root": HostClass.TENANT_SCOPED,
    "accounts:register": HostClass.TENANT_SCOPED,
    "accounts:login": HostClass.TENANT_SCOPED,
    "accounts:logout": HostClass.TENANT_SCOPED,
    "accounts:token_refresh": HostClass.TENANT_SCOPED,
    "accounts:token_verify": HostClass.TENANT_SCOPED,
    "accounts:current-user": HostClass.TENANT_SCOPED,
    "accounts:profile": HostClass.TENANT_SCOPED,
    "accounts:password-change": HostClass.TENANT_SCOPED,
    "accounts:user-statistics": HostClass.TENANT_SCOPED,
    "accounts:verify-user": HostClass.TENANT_SCOPED,
    "accounts:admin-users-list": HostClass.TENANT_SCOPED,
    "accounts:admin-users-detail": HostClass.TENANT_SCOPED,
    "accounts:admin-users-toggle-active": HostClass.TENANT_SCOPED,
    # -- Tenant-scoped: rentals (pre-rewrite draft app) --------------------
    "rentals:api-root": HostClass.TENANT_SCOPED,
    "rentals:rentals-list": HostClass.TENANT_SCOPED,
    "rentals:rentals-detail": HostClass.TENANT_SCOPED,
    "rentals:rentals-favorites": HostClass.TENANT_SCOPED,
    "rentals:rentals-my-properties": HostClass.TENANT_SCOPED,
    "rentals:rentals-toggle-favorite": HostClass.TENANT_SCOPED,
    "rentals:rentals-inquiries": HostClass.TENANT_SCOPED,
    "rentals:rental-images-list": HostClass.TENANT_SCOPED,
    "rentals:rental-images-detail": HostClass.TENANT_SCOPED,
    "rentals:rental-images-set-primary": HostClass.TENANT_SCOPED,
    "rentals:rental-inquiries-list": HostClass.TENANT_SCOPED,
    "rentals:rental-inquiries-detail": HostClass.TENANT_SCOPED,
    "rentals:rental-inquiries-reply": HostClass.TENANT_SCOPED,
    "rentals:rental-statistics": HostClass.TENANT_SCOPED,
    "rentals:admin-rentals-list": HostClass.TENANT_SCOPED,
    "rentals:admin-rentals-detail": HostClass.TENANT_SCOPED,
    "rentals:admin-rentals-toggle-featured": HostClass.TENANT_SCOPED,
    "rentals:admin-rentals-update-status": HostClass.TENANT_SCOPED,
    # -- Tenant-scoped: reviews (pre-rewrite draft app) --------------------
    "reviews:api-root": HostClass.TENANT_SCOPED,
    "reviews:reviews-list": HostClass.TENANT_SCOPED,
    "reviews:reviews-detail": HostClass.TENANT_SCOPED,
    "reviews:reviews-report": HostClass.TENANT_SCOPED,
    "reviews:reviews-vote-helpfulness": HostClass.TENANT_SCOPED,
    "reviews:reviews-my-reviews": HostClass.TENANT_SCOPED,
    "reviews:landlord-response": HostClass.TENANT_SCOPED,
    "reviews:review-statistics": HostClass.TENANT_SCOPED,
    "reviews:admin-reviews-list": HostClass.TENANT_SCOPED,
    "reviews:admin-reviews-detail": HostClass.TENANT_SCOPED,
    "reviews:admin-reviews-toggle-approval": HostClass.TENANT_SCOPED,
    "reviews:admin-reviews-toggle-verification": HostClass.TENANT_SCOPED,
    "reviews:admin-reviews-add-moderation-notes": HostClass.TENANT_SCOPED,
    "reviews:admin-reports-list": HostClass.TENANT_SCOPED,
    "reviews:admin-reports-detail": HostClass.TENANT_SCOPED,
    "reviews:admin-reports-resolve": HostClass.TENANT_SCOPED,
    "reviews:admin-reports-dismiss": HostClass.TENANT_SCOPED,
}


def classify(route_name: str | None, namespace: str = "") -> HostClass | None:
    """Return the host class for a route, or None when it is unclassified."""
    root_namespace = namespace.split(":", 1)[0]
    if root_namespace in NAMESPACE_HOST_CLASSES:
        return NAMESPACE_HOST_CLASSES[root_namespace]
    if route_name is None:
        return None
    return ROUTE_HOST_CLASSES.get(route_name)


# ---------------------------------------------------------------------------
# The single absolute-URL builder
# ---------------------------------------------------------------------------


def base_url(host_class: HostClass, *, subdomain: str | None = None) -> str:
    """Return the scheme-and-host prefix for a host class.

    ``subdomain`` is required for TENANT_SCOPED and ignored otherwise.
    """
    scheme = "https" if settings.USE_HTTPS_URLS else "http"
    root = settings.SITE_DOMAIN

    if host_class is HostClass.TENANT_SCOPED:
        if not subdomain:
            raise ValueError("A tenant-scoped URL needs the university subdomain.")
        return f"{scheme}://{subdomain}.{root}"

    if host_class is HostClass.PUBLIC_CANONICAL:
        return f"{scheme}://{settings.CANONICAL_HOST_PREFIX}.{root}"

    return f"{scheme}://{settings.INTERNAL_HOST_PREFIX}.{root}"


def build_absolute_url(
    route_name: str,
    *,
    subdomain: str | None = None,
    args: tuple = (),
    kwargs: dict | None = None,
) -> str:
    """Build an absolute URL for a named route on its correct host.

    **This is the only place in the project that may produce a scheme and host.**
    ``tests/test_architecture.py`` fails the build if anything else does —
    including ``request.build_absolute_uri``, which happily echoes back whatever
    Host header it was given and so would emit a tenant subdomain for a
    canonical link, or a canonical host for a write endpoint.
    """
    host_class = classify(route_name, namespace=route_name.split(":", 1)[0])
    if host_class is None:
        raise LookupError(
            f"Route {route_name!r} has no host class. Add it to "
            f"config.hosts.ROUTE_HOST_CLASSES — the decision is not optional."
        )
    path = reverse(route_name, args=args, kwargs=kwargs or {})
    return f"{base_url(host_class, subdomain=subdomain)}{path}"


def canonical_url(route_name: str, *, args: tuple = (), kwargs: dict | None = None) -> str:
    """The ``rel=canonical`` URL for a public listing route.

    Always the neutral host, whatever subdomain the request arrived on. That is
    the entire point of ADR-001's canonical-host resolution: one property near
    two campuses must not accumulate ranking under two different hostnames.
    """
    host_class = classify(route_name, namespace=route_name.split(":", 1)[0])
    if host_class is not HostClass.PUBLIC_CANONICAL:
        raise ValueError(
            f"Route {route_name!r} is {host_class} and has no canonical URL. "
            f"Only PUBLIC_CANONICAL routes are served from the neutral host."
        )
    path = reverse(route_name, args=args, kwargs=kwargs or {})
    return f"{base_url(HostClass.PUBLIC_CANONICAL)}{path}"
