import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { axe } from "vitest-axe";
import { describe, expect, it } from "vitest";

import { PhotoGallery } from "./PhotoGallery";
import type { Schemas } from "@/api/types";

/**
 * The gallery, tested empty first.
 *
 * The populated case is the one everybody builds and the empty one is the one
 * every listing starts in, so it is the one worth being sure about.
 */

function photo(overrides: Partial<Schemas["UnitPhoto"]> = {}): Schemas["UnitPhoto"] {
  return {
    id: 1,
    caption: "",
    sort_order: 0,
    is_primary: true,
    url: "https://cdn.test/1.jpg",
    variants: {},
    processing_status: "ready",
    ...overrides,
  };
}

describe("with no photos", () => {
  it("says so, rather than showing a placeholder image", () => {
    // A stock photo here would be the platform inventing evidence about a
    // room nobody has photographed.
    render(<PhotoGallery photos={[]} label="Photos of Bedsitters" />);

    expect(screen.getByText("No photos yet")).toBeInTheDocument();
    expect(screen.queryByRole("img")).not.toBeInTheDocument();
  });

  it("tells the reader what to do about it", () => {
    render(<PhotoGallery photos={[]} label="Photos of Bedsitters" />);

    expect(screen.getByText(/ask the landlord for photos/i)).toBeInTheDocument();
  });

  it("has no accessibility violations", async () => {
    const { container } = render(<PhotoGallery photos={[]} label="Photos" />);

    expect(await axe(container)).toHaveNoViolations();
  });
});

describe("with one photo", () => {
  it("shows no navigation at all", () => {
    // Arrows that cannot go anywhere are two tap targets that do nothing.
    render(<PhotoGallery photos={[photo()]} label="Photos" />);

    expect(screen.queryByRole("button", { name: /next photo/i })).not.toBeInTheDocument();
    expect(screen.queryByRole("button", { name: /previous photo/i })).not.toBeInTheDocument();
  });

  it("uses the caption as the alt text", () => {
    render(<PhotoGallery photos={[photo({ caption: "The shared kitchen" })]} label="Photos" />);

    expect(screen.getByAltText("The shared kitchen")).toBeInTheDocument();
  });

  it("leaves alt empty rather than inventing a description", () => {
    // The alternative is a generated "a photo of a room", which is the
    // platform describing an image it has never looked at.
    render(<PhotoGallery photos={[photo({ caption: "" })]} label="Photos" />);

    expect(screen.getByRole("presentation", { hidden: true })).toHaveAttribute("alt", "");
  });
});

describe("while a photo is still processing", () => {
  it("holds the slot instead of dropping the photo", () => {
    // ADR-007: variants are generated by a background job, so a fresh upload
    // has none and `url` can be null. Dropping it would make "4 photos" into
    // "3 photos" for reasons the landlord cannot see.
    render(
      <PhotoGallery
        photos={[photo({ id: 2, url: null, processing_status: "pending" })]}
        label="Photos"
      />,
    );

    expect(screen.getByText("Photo still uploading")).toBeInTheDocument();
  });
});

describe("with several photos", () => {
  const photos = [
    photo({ id: 1 }),
    photo({ id: 2, url: "https://cdn.test/2.jpg", is_primary: false }),
    photo({ id: 3, url: "https://cdn.test/3.jpg", is_primary: false }),
  ];

  it("announces the position in words, not only as a filled dot", () => {
    // Position carried only by which dot is filled is position carried only
    // by colour, which is the failure the whole palette exercise is about.
    render(<PhotoGallery photos={photos} label="Photos" />);

    expect(screen.getByText("Photo 1 of 3")).toBeInTheDocument();
  });

  it("moves forward and updates the announcement", async () => {
    render(<PhotoGallery photos={photos} label="Photos" />);

    await userEvent.click(screen.getByRole("button", { name: /next photo/i }));

    expect(screen.getByText("Photo 2 of 3")).toBeInTheDocument();
  });

  it("disables the arrow at each end rather than wrapping", async () => {
    // Wrapping silently loops a reader who is trying to reach the end.
    render(<PhotoGallery photos={photos} label="Photos" />);

    expect(screen.getByRole("button", { name: /previous photo/i })).toBeDisabled();

    await userEvent.click(screen.getByRole("button", { name: /next photo/i }));
    await userEvent.click(screen.getByRole("button", { name: /next photo/i }));

    expect(screen.getByRole("button", { name: /next photo/i })).toBeDisabled();
  });

  it("moves with the arrow keys", async () => {
    render(<PhotoGallery photos={photos} label="Photos" />);

    await userEvent.tab();
    await userEvent.keyboard("{ArrowRight}");

    expect(screen.getByText("Photo 2 of 3")).toBeInTheDocument();
  });

  it("has no accessibility violations", async () => {
    const { container } = render(<PhotoGallery photos={photos} label="Photos of Bedsitters" />);

    expect(await axe(container)).toHaveNoViolations();
  });
});
