# Generated by Django 5.2.17 on 2026-08-24 18:31

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('display_name', models.CharField(help_text='Short form used in the interface, e.g. "KyU".', max_length=50, verbose_name='display name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('subdomain', models.CharField(help_text='The tenant host label: "kyu" serves kyu.example.co.ke.', max_length=63, unique=True, verbose_name='subdomain')),
                ('domain', models.CharField(blank=True, help_text='The university\'s own domain, e.g. "ku.ac.ke".', max_length=255, verbose_name='institution domain')),
                ('county', models.CharField(choices=[('baringo', 'Baringo'), ('bomet', 'Bomet'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('elgeyo_marakwet', 'Elgeyo-Marakwet'), ('embu', 'Embu'), ('garissa', 'Garissa'), ('homa_bay', 'Homa Bay'), ('isiolo', 'Isiolo'), ('kajiado', 'Kajiado'), ('kakamega', 'Kakamega'), ('kericho', 'Kericho'), ('kiambu', 'Kiambu'), ('kilifi', 'Kilifi'), ('kirinyaga', 'Kirinyaga'), ('kisii', 'Kisii'), ('kisumu', 'Kisumu'), ('kitui', 'Kitui'), ('kwale', 'Kwale'), ('laikipia', 'Laikipia'), ('lamu', 'Lamu'), ('machakos', 'Machakos'), ('makueni', 'Makueni'), ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('meru', 'Meru'), ('migori', 'Migori'), ('mombasa', 'Mombasa'), ('muranga', "Murang'a"), ('nairobi', 'Nairobi'), ('nakuru', 'Nakuru'), ('nandi', 'Nandi'), ('narok', 'Narok'), ('nyamira', 'Nyamira'), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('samburu', 'Samburu'), ('siaya', 'Siaya'), ('taita_taveta', 'Taita-Taveta'), ('tana_river', 'Tana River'), ('tharaka_nithi', 'Tharaka-Nithi'), ('trans_nzoia', 'Trans Nzoia'), ('turkana', 'Turkana'), ('uasin_gishu', 'Uasin Gishu'), ('vihiga', 'Vihiga'), ('wajir', 'Wajir'), ('west_pokot', 'West Pokot')], max_length=50, verbose_name='county')),
                ('town', models.CharField(max_length=100, verbose_name='town')),
                ('logo_url', models.URLField(blank=True, verbose_name='logo URL')),
                ('favicon_url', models.URLField(blank=True, verbose_name='favicon URL')),
                ('primary_hsl', models.CharField(default='142 71% 45%', max_length=32, validators=[django.core.validators.RegexValidator(message='Use three space-separated HSL components with no wrapper, e.g. "142 71% 45%". The token system needs this exact shape.', regex='^\\d{1,3}(\\.\\d+)?\\s+\\d{1,3}(\\.\\d+)?%\\s+\\d{1,3}(\\.\\d+)?%$')], verbose_name='primary colour')),
                ('secondary_hsl', models.CharField(default='30 50% 40%', max_length=32, validators=[django.core.validators.RegexValidator(message='Use three space-separated HSL components with no wrapper, e.g. "142 71% 45%". The token system needs this exact shape.', regex='^\\d{1,3}(\\.\\d+)?\\s+\\d{1,3}(\\.\\d+)?%\\s+\\d{1,3}(\\.\\d+)?%$')], verbose_name='secondary colour')),
                ('accent_hsl', models.CharField(default='142 71% 95%', max_length=32, validators=[django.core.validators.RegexValidator(message='Use three space-separated HSL components with no wrapper, e.g. "142 71% 45%". The token system needs this exact shape.', regex='^\\d{1,3}(\\.\\d+)?\\s+\\d{1,3}(\\.\\d+)?%\\s+\\d{1,3}(\\.\\d+)?%$')], verbose_name='accent colour')),
                ('verification_methods_enabled', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email_domain', 'Student email domain'), ('student_id_upload', 'Student ID document upload')], max_length=24), blank=True, default=list, help_text='May be empty. Verification is off by default.', size=None, verbose_name='verification methods enabled')),
                ('student_email_domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Domains that prove enrolment, e.g. "s.kyu.ac.ke".', size=None, verbose_name='student email domains')),
                ('signup_policy', models.CharField(choices=[('open', 'Open — verification is not mentioned at signup'), ('verification_encouraged', 'Encouraged — the student is prompted and can skip'), ('verification_required', 'Required — signup completes only for a verified student')], default='open', help_text="Cannot be set to 'required' until at least one student here is verified, so a school cannot lock out its own intake.", max_length=24, verbose_name='signup policy')),
                ('verification_enforced_from', models.DateField(blank=True, help_text='The signup policy is inert before this date. Blank means immediately.', null=True, verbose_name='verification enforced from')),
                ('verification_required_to_review', models.BooleanField(default=False, verbose_name='verification required to review')),
                ('id_review_retention_days', models.PositiveSmallIntegerField(default=7, help_text="Uploaded ID documents are deleted this many days after a decision. Kenya's Data Protection Act 2019 obliges us to keep them no longer than necessary.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='ID document retention (days)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['subdomain', 'is_active'], name='university_subdomain_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('primary_hsl__regex', '^\\d{1,3}(\\.\\d+)?\\s+\\d{1,3}(\\.\\d+)?%\\s+\\d{1,3}(\\.\\d+)?%$')), name='university_primary_hsl_shape'), models.CheckConstraint(condition=models.Q(('secondary_hsl__regex', '^\\d{1,3}(\\.\\d+)?\\s+\\d{1,3}(\\.\\d+)?%\\s+\\d{1,3}(\\.\\d+)?%$')), name='university_secondary_hsl_shape'), models.CheckConstraint(condition=models.Q(('accent_hsl__regex', '^\\d{1,3}(\\.\\d+)?\\s+\\d{1,3}(\\.\\d+)?%\\s+\\d{1,3}(\\.\\d+)?%$')), name='university_accent_hsl_shape'), models.CheckConstraint(condition=models.Q(('id_review_retention_days__gte', 1), ('id_review_retention_days__lte', 90)), name='university_retention_window_sane')],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('town', models.CharField(max_length=100, verbose_name='town')),
                ('county', models.CharField(choices=[('baringo', 'Baringo'), ('bomet', 'Bomet'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('elgeyo_marakwet', 'Elgeyo-Marakwet'), ('embu', 'Embu'), ('garissa', 'Garissa'), ('homa_bay', 'Homa Bay'), ('isiolo', 'Isiolo'), ('kajiado', 'Kajiado'), ('kakamega', 'Kakamega'), ('kericho', 'Kericho'), ('kiambu', 'Kiambu'), ('kilifi', 'Kilifi'), ('kirinyaga', 'Kirinyaga'), ('kisii', 'Kisii'), ('kisumu', 'Kisumu'), ('kitui', 'Kitui'), ('kwale', 'Kwale'), ('laikipia', 'Laikipia'), ('lamu', 'Lamu'), ('machakos', 'Machakos'), ('makueni', 'Makueni'), ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('meru', 'Meru'), ('migori', 'Migori'), ('mombasa', 'Mombasa'), ('muranga', "Murang'a"), ('nairobi', 'Nairobi'), ('nakuru', 'Nakuru'), ('nandi', 'Nandi'), ('narok', 'Narok'), ('nyamira', 'Nyamira'), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('samburu', 'Samburu'), ('siaya', 'Siaya'), ('taita_taveta', 'Taita-Taveta'), ('tana_river', 'Tana River'), ('tharaka_nithi', 'Tharaka-Nithi'), ('trans_nzoia', 'Trans Nzoia'), ('turkana', 'Turkana'), ('uasin_gishu', 'Uasin Gishu'), ('vihiga', 'Vihiga'), ('wajir', 'Wajir'), ('west_pokot', 'West Pokot')], max_length=50, verbose_name='county')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('is_main', models.BooleanField(default=False, verbose_name='main campus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='universities.university', verbose_name='university')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'ordering': ['university', 'name'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('university', 'name'), name='campus_unique_name_per_university'), models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('university',), name='campus_one_main_per_university'), models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='campus_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='campus_longitude_range')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
