# Generated by Django 5.2.17 on 2026-08-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='join_radius_km',
            field=models.FloatField(blank=True, help_text='How far a property can be from this campus and still be listed against it. Blank uses the platform default (CAMPUS_JOIN_RADIUS_KM). A city campus with dense housing next door and a rural one where students commute from the nearest town are not the same question, and one number for both is a decision nobody made.', null=True, verbose_name='join radius (km)'),
        ),
    ]
