# Generated by Django 5.2.17 on 2026-08-24 19:52

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('universities', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('property_type', models.CharField(choices=[('bedsitter', 'Bedsitter'), ('single_room', 'Single Room'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('three_bedroom', 'Three Bedroom'), ('hostel_block', 'Hostel Block'), ('shared_house', 'Shared House'), ('maisonette', 'Maisonette'), ('other', 'Other')], max_length=20, verbose_name='property type')),
                ('county', models.CharField(choices=[('baringo', 'Baringo'), ('bomet', 'Bomet'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('elgeyo_marakwet', 'Elgeyo-Marakwet'), ('embu', 'Embu'), ('garissa', 'Garissa'), ('homa_bay', 'Homa Bay'), ('isiolo', 'Isiolo'), ('kajiado', 'Kajiado'), ('kakamega', 'Kakamega'), ('kericho', 'Kericho'), ('kiambu', 'Kiambu'), ('kilifi', 'Kilifi'), ('kirinyaga', 'Kirinyaga'), ('kisii', 'Kisii'), ('kisumu', 'Kisumu'), ('kitui', 'Kitui'), ('kwale', 'Kwale'), ('laikipia', 'Laikipia'), ('lamu', 'Lamu'), ('machakos', 'Machakos'), ('makueni', 'Makueni'), ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('meru', 'Meru'), ('migori', 'Migori'), ('mombasa', 'Mombasa'), ('muranga', "Murang'a"), ('nairobi', 'Nairobi'), ('nakuru', 'Nakuru'), ('nandi', 'Nandi'), ('narok', 'Narok'), ('nyamira', 'Nyamira'), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('samburu', 'Samburu'), ('siaya', 'Siaya'), ('taita_taveta', 'Taita-Taveta'), ('tana_river', 'Tana River'), ('tharaka_nithi', 'Tharaka-Nithi'), ('trans_nzoia', 'Trans Nzoia'), ('turkana', 'Turkana'), ('uasin_gishu', 'Uasin Gishu'), ('vihiga', 'Vihiga'), ('wajir', 'Wajir'), ('west_pokot', 'West Pokot')], max_length=50, verbose_name='county')),
                ('town', models.CharField(max_length=100, verbose_name='town')),
                ('estate', models.CharField(help_text='e.g. "Kahawa Wendani"', max_length=100, verbose_name='estate')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='street')),
                ('landmark', models.CharField(blank=True, help_text='e.g. "opposite Naivas"', max_length=200, verbose_name='landmark')),
                ('postal_address', models.CharField(blank=True, help_text='P.O. Box 43844-00100', max_length=50, verbose_name='postal address')),
                ('latitude', models.FloatField(blank=True, help_text='Map pins and distance computation only. Never queried directly (ADR-006).', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('has_water_tank', models.BooleanField(default=False, verbose_name='water tank')),
                ('has_borehole', models.BooleanField(default=False, verbose_name='borehole')),
                ('has_backup_power', models.BooleanField(default=False, verbose_name='backup power')),
                ('has_perimeter_wall', models.BooleanField(default=False, verbose_name='perimeter wall')),
                ('has_security_guard', models.BooleanField(default=False, verbose_name='security guard')),
                ('has_cctv', models.BooleanField(default=False, verbose_name='CCTV')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='wifi')),
                ('has_parking', models.BooleanField(default=False, verbose_name='parking')),
                ('caretaker_on_site', models.BooleanField(default=False, verbose_name='caretaker on site')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='accounts.landlordprofile', verbose_name='landlord')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('published_at'), descending=True, nulls_first=True), '-created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCampusDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straight_line_km', models.DecimalField(decimal_places=2, help_text='Haversine, computed on save. Always present, and an honest lower bound. Any UI showing it must label it as direct distance.', max_digits=5, verbose_name='straight-line distance (km)')),
                ('walking_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='From a routing provider only. Never derived from the straight line.', max_digits=5, null=True, verbose_name='walking distance (km)')),
                ('walking_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='walking minutes')),
                ('routed_at', models.DateTimeField(blank=True, null=True, verbose_name='routed at')),
                ('route_provider', models.CharField(blank=True, max_length=32, verbose_name='route provider')),
                ('matatu_route', models.CharField(blank=True, help_text='e.g. "Route 45"', max_length=50, verbose_name='matatu route')),
                ('is_primary', models.BooleanField(default=False, help_text='The campus this listing is marketed against.', verbose_name='primary campus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_distances', to='universities.campus')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_distances', to='properties.property', verbose_name='property')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_distances', to='universities.university')),
            ],
            options={
                'verbose_name': 'Property/campus distance',
                'verbose_name_plural': 'Property/campus distances',
                'ordering': ['property', 'straight_line_km'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='"B12" for one unit, or "Bedsitters" for a pool of identical ones.', max_length=50, verbose_name='label')),
                ('unit_type', models.CharField(choices=[('bedsitter', 'Bedsitter'), ('single_room', 'Single Room'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('three_bedroom', 'Three Bedroom'), ('hostel_block', 'Hostel Block'), ('shared_house', 'Shared House'), ('maisonette', 'Maisonette'), ('other', 'Other')], max_length=20, verbose_name='unit type')),
                ('rent_kes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monthly rent (KES)')),
                ('deposit_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='deposit (KES)')),
                ('water_included', models.BooleanField(default=False, verbose_name='water included')),
                ('electricity_included', models.BooleanField(default=False, help_text='Token metering is the norm otherwise.', verbose_name='electricity included')),
                ('wifi_included', models.BooleanField(default=False, verbose_name='wifi included')),
                ('furnished', models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi Furnished'), ('furnished', 'Furnished')], default='unfurnished', max_length=20, verbose_name='furnishing')),
                ('size_sqm', models.PositiveSmallIntegerField(blank=True, help_text='Square metres, not feet.', null=True, verbose_name='size (m²)')),
                ('bedrooms', models.PositiveSmallIntegerField(default=0, help_text='0 for a bedsitter or single room.', verbose_name='bedrooms')),
                ('has_private_bathroom', models.BooleanField(default=False, help_text="Replaces the draft's bathrooms>=1, which made a hostel block with shared ablutions impossible to list.", verbose_name='private bathroom')),
                ('has_kitchenette', models.BooleanField(default=False, verbose_name='kitchenette')),
                ('floor', models.SmallIntegerField(blank=True, null=True, verbose_name='floor')),
                ('total_count', models.PositiveSmallIntegerField(default=1, help_text='How many identical units exist.', verbose_name='total units')),
                ('vacant_count', models.PositiveSmallIntegerField(default=0, help_text='How many are free right now.', verbose_name='vacant units')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='available from')),
                ('min_stay_months', models.PositiveSmallIntegerField(default=4, help_text='One semester. The draft defaulted to a 12-month lease.', verbose_name='minimum stay (months)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property', verbose_name='property')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['property', 'label'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UnitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_key', models.CharField(help_text='Object key in the public media bucket.', max_length=500, verbose_name='original key')),
                ('thumb_key', models.CharField(blank=True, max_length=500, verbose_name='thumbnail key')),
                ('medium_key', models.CharField(blank=True, max_length=500, verbose_name='medium key')),
                ('large_key', models.CharField(blank=True, max_length=500, verbose_name='large key')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='processing status')),
                ('processing_error', models.CharField(blank=True, max_length=255, verbose_name='processing error')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary photo')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='height')),
                ('byte_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Unit photo',
                'verbose_name_plural': 'Unit photos',
                'ordering': ['unit', 'sort_order', 'created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', '-published_at'], name='property_status_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['county', 'town'], name='property_location_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['landlord', 'status'], name='property_landlord_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='property_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='property_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='property_published_has_timestamp'),
        ),
        migrations.AddIndex(
            model_name='propertycampusdistance',
            index=models.Index(fields=['university', 'straight_line_km'], name='pcd_university_distance_idx'),
        ),
        migrations.AddIndex(
            model_name='propertycampusdistance',
            index=models.Index(fields=['routed_at'], name='pcd_routed_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertycampusdistance',
            constraint=models.UniqueConstraint(fields=('property', 'campus'), name='pcd_unique_property_campus'),
        ),
        migrations.AddConstraint(
            model_name='propertycampusdistance',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('property',), name='pcd_one_primary_campus_per_property'),
        ),
        migrations.AddConstraint(
            model_name='propertycampusdistance',
            constraint=models.CheckConstraint(condition=models.Q(('straight_line_km__gte', 0), ('straight_line_km__lte', 500)), name='pcd_distance_sane'),
        ),
        migrations.AddConstraint(
            model_name='propertycampusdistance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('walking_minutes__isnull', True), ('walking_distance_km__isnull', True), ('routed_at__isnull', True)), models.Q(('walking_minutes__isnull', False), ('walking_distance_km__isnull', False), ('routed_at__isnull', False)), _connector='OR'), name='pcd_routed_fields_move_together'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['property', 'is_active'], name='unit_property_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['rent_kes'], name='unit_rent_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_type', 'rent_kes'], name='unit_type_rent_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('property', 'label'), name='unit_label_unique_per_property'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('vacant_count__lte', models.F('total_count'))), name='unit_vacant_not_over_total'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('rent_kes__gt', 0)), name='unit_rent_positive'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_kes__isnull', True), ('deposit_kes__gte', 0), _connector='OR'), name='unit_deposit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('total_count__gte', 1)), name='unit_total_count_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('min_stay_months__gte', 1)), name='unit_min_stay_at_least_one_month'),
        ),
        migrations.AddIndex(
            model_name='unitphoto',
            index=models.Index(fields=['unit', 'sort_order'], name='unitphoto_order_idx'),
        ),
        migrations.AddIndex(
            model_name='unitphoto',
            index=models.Index(fields=['processing_status', 'created_at'], name='unitphoto_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('unit',), name='unitphoto_one_primary_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='unitphoto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('processing_status', 'ready'), _negated=True), models.Q(models.Q(('thumb_key', ''), _negated=True), models.Q(('medium_key', ''), _negated=True), models.Q(('large_key', ''), _negated=True)), _connector='OR'), name='unitphoto_ready_has_all_variants'),
        ),
        migrations.AddConstraint(
            model_name='unitphoto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('processing_status', 'failed'), _negated=True), models.Q(('processing_error', ''), _negated=True), _connector='OR'), name='unitphoto_failed_has_a_reason'),
        ),
    ]
