# Generated by Django 5.2.17 on 2026-08-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('suspended', 'Suspended'), ('archived', 'Archived'), ('dormant', "Dormant — the owner's account was erased")], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
