# Generated by Django 5.2.17 on 2026-08-27 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='vacant_count_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='vacancy updated at'),
        ),
        migrations.AddField(
            model_name='unit',
            name='vacant_count_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancy_updates', to=settings.AUTH_USER_MODEL, verbose_name='vacancy updated by'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='vacant_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many are free right now, AS STATED BY THE LANDLORD. Never derived and never overwritten: they know about the room let last week off-platform and we do not, so their number is usually better than anything we could compute.', verbose_name='vacant units'),
        ),
    ]
