"""
Property and unit serializers (ADR-002, ADR-007).

Read-only. Listings are written through the landlord dashboard, which is not
this round; what a student sees is here.

Two things carry contract notes into the generated TypeScript, because both are
mistakes a frontend makes by default: `straight_line_km` is not a walking
distance, and `walking_minutes` is legitimately null and must render as an em
dash rather than a zero.
"""

from __future__ import annotations

from drf_spectacular.utils import extend_schema_field
from rest_framework import serializers

from config.api.contract import (
    STRAIGHT_LINE_KM,
    VACANCY_AGE_DAYS,
    VACANCY_FRESHNESS,
    WALKING_MINUTES,
)
from universities.models import Campus

from .constants import PHOTO_VARIANTS
from .models import Property, PropertyCampusDistance, Unit, UnitPhoto


class UnitPhotoSerializer(serializers.ModelSerializer):
    """One photo, with whichever variants exist.

    Variants are generated by a background job (ADR-007), so a freshly uploaded
    photo has none. `url` always resolves -- to a variant when one exists, to
    the original otherwise -- so a slow queue costs page weight rather than a
    broken image.
    """

    url = serializers.SerializerMethodField(
        help_text="Best available rendition. Never null for a ready photo."
    )
    variants = serializers.SerializerMethodField(
        help_text=(
            "Available renditions by name. May be empty while the resize job "
            "is still queued; fall back to `url`."
        )
    )

    class Meta:
        model = UnitPhoto
        fields = (
            "id",
            "caption",
            "sort_order",
            "is_primary",
            "url",
            "variants",
            "processing_status",
        )
        read_only_fields = fields

    @extend_schema_field(serializers.CharField(allow_null=True))
    def get_url(self, photo: UnitPhoto) -> str | None:
        return photo.best_url()

    @extend_schema_field(serializers.DictField(child=serializers.CharField()))
    def get_variants(self, photo: UnitPhoto) -> dict[str, str]:
        return {
            variant: photo.variant_url(variant)
            for variant in PHOTO_VARIANTS
            if photo.variant_url(variant)
        }


class CampusDistanceSerializer(serializers.ModelSerializer):
    """How far a property is from one campus.

    Both numbers are here on purpose and they are not interchangeable.
    """

    campus_name = serializers.CharField(source="campus.name", read_only=True)
    university_name = serializers.CharField(source="university.name", read_only=True)
    straight_line_km = serializers.DecimalField(
        max_digits=6, decimal_places=2, read_only=True, help_text=STRAIGHT_LINE_KM
    )
    walking_minutes = serializers.IntegerField(
        read_only=True, allow_null=True, help_text=WALKING_MINUTES
    )
    walking_distance_km = serializers.DecimalField(
        max_digits=6,
        decimal_places=2,
        read_only=True,
        allow_null=True,
        help_text=(
            "Routed walking distance in kilometres. Null for the same reasons "
            "as walking_minutes; never substituted with the straight line."
        ),
    )

    class Meta:
        model = PropertyCampusDistance
        fields = (
            "campus_name",
            "university_name",
            "straight_line_km",
            "walking_distance_km",
            "walking_minutes",
            "route_provider",
            "routed_at",
        )
        read_only_fields = fields


class UnitSummarySerializer(serializers.ModelSerializer):
    """A unit as it appears inside a property listing."""

    is_available = serializers.SerializerMethodField(
        help_text=(
            "Whether any of this unit's rooms are free. Derived from "
            "vacant_count -- a Unit row may represent a POOL of identical "
            "rooms, so 'has a tenancy' is not the same question."
        )
    )
    vacancy_freshness = serializers.SerializerMethodField(help_text=VACANCY_FRESHNESS)
    vacancy_age_days = serializers.SerializerMethodField(help_text=VACANCY_AGE_DAYS)

    class Meta:
        model = Unit
        fields: tuple[str, ...] = (
            "id",
            "label",
            "unit_type",
            "rent_kes",
            "deposit_kes",
            "furnished",
            "bedrooms",
            "size_sqm",
            "total_count",
            "vacant_count",
            "is_available",
            "vacancy_freshness",
            "vacancy_age_days",
            "available_from",
            "min_stay_months",
        )
        read_only_fields: tuple[str, ...] = fields

    @extend_schema_field(serializers.BooleanField())
    def get_is_available(self, unit: Unit) -> bool:
        return unit.is_available()

    @extend_schema_field(serializers.ChoiceField(choices=["fresh", "ageing", "stale", "unknown"]))
    def get_vacancy_freshness(self, unit: Unit) -> str:
        from .services import vacancy_freshness

        return vacancy_freshness(unit)

    @extend_schema_field(serializers.IntegerField(allow_null=True))
    def get_vacancy_age_days(self, unit: Unit) -> int | None:
        from .services import vacancy_age_days

        return vacancy_age_days(unit)


class UnitDetailSerializer(UnitSummarySerializer):
    """One unit, with its photos and its property's identity."""

    photos = UnitPhotoSerializer(many=True, read_only=True)
    property_id = serializers.IntegerField(source="property.id", read_only=True)
    property_name = serializers.CharField(source="property.name", read_only=True)

    class Meta(UnitSummarySerializer.Meta):
        fields = (
            *UnitSummarySerializer.Meta.fields,
            "water_included",
            "electricity_included",
            "wifi_included",
            "has_private_bathroom",
            "has_kitchenette",
            "floor",
            "photos",
            "property_id",
            "property_name",
        )
        read_only_fields = fields


class PropertySummarySerializer(serializers.ModelSerializer):
    """A property in a search result.

    `nearest_campus_km` is annotated by the ordering helper and is present only
    when the queryset was ordered by distance. Absent, not null, otherwise --
    so a client can tell "not requested" from "no campus".
    """

    nearest_campus_km = serializers.DecimalField(
        max_digits=6,
        decimal_places=2,
        read_only=True,
        required=False,
        help_text=(
            "Straight-line kilometres to the nearest campus of the current "
            "university. Present only when ordering by distance."
        ),
    )
    cheapest_rent_kes = serializers.DecimalField(
        max_digits=10, decimal_places=2, read_only=True, allow_null=True, required=False
    )
    cover_photo_url = serializers.SerializerMethodField()

    class Meta:
        model = Property
        fields: tuple[str, ...] = (
            "id",
            "name",
            "slug",
            "property_type",
            "county",
            "town",
            "estate",
            "landmark",
            "latitude",
            "longitude",
            "has_water_tank",
            "has_borehole",
            "has_backup_power",
            "has_perimeter_wall",
            "has_security_guard",
            "has_wifi",
            "caretaker_on_site",
            "published_at",
            "nearest_campus_km",
            "cheapest_rent_kes",
            "cover_photo_url",
        )
        read_only_fields: tuple[str, ...] = fields

    @extend_schema_field(serializers.CharField(allow_null=True))
    def get_cover_photo_url(self, prop: Property) -> str | None:
        photo = getattr(prop, "cover_photo", None)
        return photo.best_url() if photo else None


class PropertyDetailSerializer(PropertySummarySerializer):
    """One property, with its units and campus distances."""

    units = UnitSummarySerializer(many=True, read_only=True)
    campus_distances = CampusDistanceSerializer(many=True, read_only=True)
    landlord_name = serializers.SerializerMethodField(
        help_text=(
            "Display name of the owner. Reads 'Former landlord' for an erased "
            "account (ADR-008) -- the listing survives the person."
        )
    )

    class Meta(PropertySummarySerializer.Meta):
        fields = (
            *PropertySummarySerializer.Meta.fields,
            "description",
            "street",
            "has_cctv",
            "has_parking",
            "units",
            "campus_distances",
            "landlord_name",
            "view_count",
        )
        read_only_fields = fields

    @extend_schema_field(serializers.CharField())
    def get_landlord_name(self, prop: Property) -> str:
        from accounts.privacy import display_name_for

        return display_name_for(prop.landlord.user)


class CampusSerializer(serializers.ModelSerializer):
    class Meta:
        model = Campus
        fields = ("id", "name", "town", "county", "latitude", "longitude", "is_main")
        read_only_fields = fields
