/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/admin/statistics/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * User statistics
         * @description Counts by capability rather than by a self-declared string.
         */
        get: operations["auth_admin_statistics_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User administration for platform staff. */
        get: operations["auth_admin_users_list"];
        put?: never;
        /** @description User administration for platform staff. */
        post: operations["auth_admin_users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User administration for platform staff. */
        get: operations["auth_admin_users_retrieve"];
        /** @description User administration for platform staff. */
        put: operations["auth_admin_users_update"];
        post?: never;
        /** @description User administration for platform staff. */
        delete: operations["auth_admin_users_destroy"];
        options?: never;
        head?: never;
        /** @description User administration for platform staff. */
        patch: operations["auth_admin_users_partial_update"];
        trace?: never;
    };
    "/api/v1/auth/admin/users/{id}/toggle_active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle active
         * @description User administration for platform staff.
         */
        post: operations["auth_admin_users_toggle_active_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin/verify/{user_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a landlord
         * @description Mark a landlord profile verified.
         *
         *     Landlord verification is a platform-staff action. Student verification is
         *     a different flow entirely, run per-university (ADR-003).
         */
        post: operations["auth_admin_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Blacklist the refresh token.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Identity and the caller's capability set (ADR-003).
         */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password */
        post: operations["auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get profile
         * @description The caller's own identity.
         */
        get: operations["auth_profile_retrieve"];
        /**
         * Replace profile
         * @description PUT is supported as well as PATCH.
         *
         *     The previous frontend called PUT here and got a 405 on every profile
         *     save, because the draft implemented only GET and PATCH
         *     (docs/AUDIT.md §5).
         */
        put: operations["auth_profile_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update profile
         * @description The caller's own identity.
         */
        patch: operations["auth_profile_partial_update"];
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account and return tokens.
         */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
        post: operations["auth_token_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/config/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tenant configuration
         * @description Branding and identity for the university serving this host. Unauthenticated: the login page itself has to be branded, and it renders before any token exists. Returns 404 on a host that resolves no tenant, so the client falls back to its neutral palette.
         */
        get: operations["tenant_config_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 whenever the process can serve a request.
         */
        get: operations["health_live_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 when the database and Redis are both reachable, 503 otherwise.
         */
        get: operations["health_ready_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description User administration, for platform staff.
         *
         *     ``is_staff`` stays read-only here too: elevating a user to platform staff
         *     is a Django admin or management-command action, never an API one.
         */
        AdminUser: {
            readonly id: number;
            /**
             * Email address
             * Format: email
             */
            readonly email: string;
            first_name: string;
            last_name: string;
            readonly full_name: string;
            phone_number?: string;
            /** Active */
            is_active?: boolean;
            /**
             * Platform staff
             * @description The only meaning of 'platform administrator'. Not settable via the API.
             */
            readonly is_staff: boolean;
            /** Format: date-time */
            readonly date_joined: string;
            /**
             * @description The shape ``/auth/me/`` returns.
             *
             *     Explicit rather than derived client-side, so the client never has to know
             *     what a LandlordProfile is.
             */
            readonly capabilities: {
                is_student: boolean;
                is_landlord: boolean;
                is_university_staff: boolean;
                is_staff: boolean;
                is_verified_student: boolean;
                verification_status: string | null;
                grace_period_ends_at: string | null;
                university: string | null;
                manages_properties: number[];
            };
        };
        /**
         * @description User administration, for platform staff.
         *
         *     ``is_staff`` stays read-only here too: elevating a user to platform staff
         *     is a Django admin or management-command action, never an API one.
         */
        AdminUserRequest: {
            first_name: string;
            last_name: string;
            phone_number?: string;
            /** Active */
            is_active?: boolean;
        };
        PaginatedAdminUserList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminUser"][];
        };
        PasswordChangeRequest: {
            current_password: string;
            new_password: string;
            new_password_confirm: string;
        };
        /**
         * @description User administration, for platform staff.
         *
         *     ``is_staff`` stays read-only here too: elevating a user to platform staff
         *     is a Django admin or management-command action, never an API one.
         */
        PatchedAdminUserRequest: {
            first_name?: string;
            last_name?: string;
            phone_number?: string;
            /** Active */
            is_active?: boolean;
        };
        /**
         * @description The fields a user may change about themselves.
         *
         *     Deliberately short. Nothing here grants any capability: that is the point
         *     of ADR-003, and a registration or profile payload must never be able to
         *     escalate.
         */
        PatchedUserUpdateRequest: {
            first_name?: string;
            last_name?: string;
            phone_number?: string;
            /** Format: uri */
            avatar_url?: string;
        };
        /**
         * @description The public tenant configuration (ADR-005).
         *
         *     Deliberately small. It is fetched before first paint on every cold visit,
         *     so anything not needed to render the shell does not belong here.
         */
        TenantConfig: {
            /** @description The tenant host label: "kyu" serves kyu.example.co.ke. */
            readonly subdomain: string;
            readonly name: string;
            /** @description Short form used in the interface, e.g. "KyU". */
            readonly display_name: string;
            /** Format: uri */
            readonly logo_url: string;
            /** Format: uri */
            readonly favicon_url: string;
            readonly theme: components["schemas"]["TenantTheme"];
        };
        /**
         * @description The three tokens ADR-005 overrides.
         *
         *     Foregrounds, `--ring` and the light/dark primary variants are derived
         *     client-side by WCAG contrast rather than sent, so a tenant cannot configure
         *     an unreadable button.
         */
        TenantTheme: {
            /** @description HSL triple, e.g. "142 71% 45%". */
            primary: string;
            secondary: string;
            accent: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        TokenVerifyRequest: {
            token: string;
        };
        /** @description A user's own identity, with their capability set. */
        User: {
            readonly id: number;
            /**
             * Email address
             * Format: email
             */
            readonly email: string;
            first_name: string;
            last_name: string;
            readonly full_name: string;
            phone_number?: string;
            readonly phone_verified: boolean;
            readonly email_verified: boolean;
            /** Format: uri */
            avatar_url?: string;
            /** Active */
            readonly is_active: boolean;
            /** Format: date-time */
            readonly date_joined: string;
            /**
             * @description The shape ``/auth/me/`` returns.
             *
             *     Explicit rather than derived client-side, so the client never has to know
             *     what a LandlordProfile is.
             */
            readonly capabilities: {
                is_student: boolean;
                is_landlord: boolean;
                is_university_staff: boolean;
                is_staff: boolean;
                is_verified_student: boolean;
                verification_status: string | null;
                grace_period_ends_at: string | null;
                university: string | null;
                manages_properties: number[];
            };
        };
        /** @description Exchange credentials for a user. */
        UserLoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /**
         * @description Create an account.
         *
         *     No role field. The draft accepted ``user_type`` straight from the request
         *     body and never validated it, so anyone could register as an administrator
         *     and the object-permission checks trusted it (docs/AUDIT.md §4.4).
         *
         *     When the request resolves a tenant, the new user gets a StudentProfile for
         *     that university — signing up on a university's own subdomain is the
         *     statement that you are its student. Landlord and staff profiles are granted,
         *     never self-declared.
         */
        UserRegistrationRequest: {
            /**
             * Email address
             * Format: email
             */
            email: string;
            password: string;
            password_confirm: string;
            first_name: string;
            last_name: string;
            phone_number?: string;
        };
        /**
         * @description The fields a user may change about themselves.
         *
         *     Deliberately short. Nothing here grants any capability: that is the point
         *     of ADR-003, and a registration or profile payload must never be able to
         *     escalate.
         */
        UserUpdateRequest: {
            first_name: string;
            last_name: string;
            phone_number?: string;
            /** Format: uri */
            avatar_url?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_admin_statistics_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_admin_users_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminUserList"];
                };
            };
        };
    };
    auth_admin_users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminUserRequest"];
                "multipart/form-data": components["schemas"]["AdminUserRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    auth_admin_users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this User. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    auth_admin_users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this User. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminUserRequest"];
                "multipart/form-data": components["schemas"]["AdminUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    auth_admin_users_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this User. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_admin_users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this User. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAdminUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedAdminUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    auth_admin_users_toggle_active_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this User. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_admin_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserLoginRequest"];
                "multipart/form-data": components["schemas"]["UserLoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChangeRequest"];
                "multipart/form-data": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserUpdateRequest"];
                "multipart/form-data": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegistrationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRegistrationRequest"];
                "multipart/form-data": components["schemas"]["UserRegistrationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    auth_token_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerifyRequest"];
                "multipart/form-data": components["schemas"]["TokenVerifyRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tenant_config_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantConfig"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_live_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_ready_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
