# Generated by Django 5.2.17 on 2026-08-25 06:58

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import reviews.aggregates
import reviews.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('properties', '0001_initial'),
        ('tenancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='overall rating')),
                ('cleanliness_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='cleanliness')),
                ('security_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='security')),
                ('water_reliability_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='water reliability')),
                ('landlord_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='landlord')),
                ('value_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='value for money')),
                ('comment', models.TextField(blank=True, max_length=2000, verbose_name='comment')),
                ('would_recommend', models.BooleanField(blank=True, null=True, verbose_name='would recommend')),
                ('editable_until', models.DateTimeField(default=reviews.models._default_editable_until, verbose_name='editable until')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('hidden_reason', models.CharField(blank=True, max_length=200, verbose_name='hidden reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenancy', models.OneToOneField(help_text='The stay being reviewed. Not nullable: it is the whole point.', on_delete=django.db.models.deletion.PROTECT, related_name='review', to='tenancies.tenancy')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000, verbose_name='response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_responses', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='reviews.review')),
            ],
            options={
                'verbose_name': 'Review response',
                'verbose_name_plural': 'Review responses',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UnitRatingAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Null means no verified reviews yet. Never a default score.', max_digits=3, null=True, verbose_name='average rating')),
                ('student_count', models.PositiveIntegerField(default=0, verbose_name='students')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='reviews')),
                ('rating_distribution', models.JSONField(default=reviews.aggregates._empty_distribution, verbose_name='rating distribution')),
                ('last_review_at', models.DateTimeField(blank=True, null=True, verbose_name='last review at')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='computed at')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_aggregate', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Unit rating',
                'verbose_name_plural': 'Unit ratings',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LandlordRatingAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Null means no verified reviews yet. Never a default score.', max_digits=3, null=True, verbose_name='average rating')),
                ('student_count', models.PositiveIntegerField(default=0, verbose_name='students')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='reviews')),
                ('rating_distribution', models.JSONField(default=reviews.aggregates._empty_distribution, verbose_name='rating distribution')),
                ('last_review_at', models.DateTimeField(blank=True, null=True, verbose_name='last review at')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='computed at')),
                ('property_count', models.PositiveIntegerField(default=0, verbose_name='properties')),
                ('landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_aggregate', to='accounts.landlordprofile')),
            ],
            options={
                'verbose_name': 'Landlord rating',
                'verbose_name_plural': 'Landlord ratings',
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('average_rating__isnull', True), models.Q(('average_rating__gte', 1), ('average_rating__lte', 5)), _connector='OR'), name='landlord_aggregate_rating_range'), models.CheckConstraint(condition=models.Q(('student_count__lte', models.F('review_count'))), name='landlord_aggregate_students_within_reviews'), models.CheckConstraint(condition=models.Q(('review_count__gt', 0), ('average_rating__isnull', True), _connector='OR'), name='landlord_aggregate_empty_has_no_score')],
            },
        ),
        migrations.CreateModel(
            name='PropertyRatingAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Null means no verified reviews yet. Never a default score.', max_digits=3, null=True, verbose_name='average rating')),
                ('student_count', models.PositiveIntegerField(default=0, verbose_name='students')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='reviews')),
                ('rating_distribution', models.JSONField(default=reviews.aggregates._empty_distribution, verbose_name='rating distribution')),
                ('last_review_at', models.DateTimeField(blank=True, null=True, verbose_name='last review at')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='computed at')),
                ('property_reviewed', models.OneToOneField(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='rating_aggregate', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property rating',
                'verbose_name_plural': 'Property ratings',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['-average_rating'], name='prop_rating_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('average_rating__isnull', True), models.Q(('average_rating__gte', 1), ('average_rating__lte', 5)), _connector='OR'), name='property_aggregate_rating_range'), models.CheckConstraint(condition=models.Q(('student_count__lte', models.F('review_count'))), name='property_aggregate_students_within_reviews'), models.CheckConstraint(condition=models.Q(('review_count__gt', 0), ('average_rating__isnull', True), _connector='OR'), name='property_aggregate_empty_has_no_score')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_published', '-created_at'], name='review_published_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('cleanliness_rating__isnull', True), models.Q(('cleanliness_rating__gte', 1), ('cleanliness_rating__lte', 5)), _connector='OR'), name='review_cleanliness_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('security_rating__isnull', True), models.Q(('security_rating__gte', 1), ('security_rating__lte', 5)), _connector='OR'), name='review_security_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('water_reliability_rating__isnull', True), models.Q(('water_reliability_rating__gte', 1), ('water_reliability_rating__lte', 5)), _connector='OR'), name='review_water_reliability_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('landlord_rating__isnull', True), models.Q(('landlord_rating__gte', 1), ('landlord_rating__lte', 5)), _connector='OR'), name='review_landlord_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('value_rating__isnull', True), models.Q(('value_rating__gte', 1), ('value_rating__lte', 5)), _connector='OR'), name='review_value_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('is_published', True), models.Q(('hidden_reason', ''), _negated=True), _connector='OR'), name='review_hidden_states_why'),
        ),
        migrations.AddConstraint(
            model_name='reviewresponse',
            constraint=models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='review_response_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='unitratingaggregate',
            constraint=models.CheckConstraint(condition=models.Q(('average_rating__isnull', True), models.Q(('average_rating__gte', 1), ('average_rating__lte', 5)), _connector='OR'), name='unit_aggregate_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='unitratingaggregate',
            constraint=models.CheckConstraint(condition=models.Q(('student_count__lte', models.F('review_count'))), name='unit_aggregate_students_within_reviews'),
        ),
        migrations.AddConstraint(
            model_name='unitratingaggregate',
            constraint=models.CheckConstraint(condition=models.Q(('review_count__gt', 0), ('average_rating__isnull', True), _connector='OR'), name='unit_aggregate_empty_has_no_score'),
        ),
    ]
